name: Discord PR tracking
on: [pull_request_review]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks
        uses: actions/checkout@v2
        with:
          path: shop_demo
          persist-credentials: false
      - name: Send PR status to Discord
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANEL: ${{ secrets.DISCORD_CHANEL }}
        run: |
          cd shop_demo
          python3 advertise_to_discord.py $DISCORD_TOKEN $DISCORD_CHANEL $PR_NUMBER $PR_AUTHOR "$PR_TITLE"
