name: Discord PR tracking
on:
  pull_request_target:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks
        uses: actions/checkout@v2
        with:
          path: shop_demo
          persist-credentials: false
      - name: Send PR status to Discord
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        DISCORD_TOKEN: ${{ secret.DISCORD_TOKEN }}
        DISCORD_CHANEL: ${{ secret.DISCORD_CHANEL }}
      run: |
        cd ivy/automation_tools/tools/pr_discord_tracking
        python3 advertise_to_discord.py $DISCORD_TOKEN $DISCORD_CHANEL