on:
  pull_request:
    branches: main
    types: [opened]

jobs:
  pull_request_labeling_linking:
    name: PR Labeling and Linking
    runs-on: ubuntu-latest
    steps:
      - name: Checks
        uses: actions/checkout@v2
